### ISSUE TITLE
How to extract image features using ResNet101 under tensorflow

### ISSUE THREAD

**Issue by flyinsky323** [minar09/DeepLabV2-ResNet101-TensorFlow#1]
How to extract image features using ResNet101 under tensorflow？

**Comment by minar09** [comment]
> How to extract image features using ResNet101 under tensorflow？

@flyinsky323, Could you please be more specific what you are trying to do? Anyway, this repository is just slightly modified version of this: https://github.com/DrSleep/tensorflow-deeplab-resnet, for working with python 3. You may find your answers from the original repository discussions as well.

**Comment by flyinsky323** [comment]
I need to extract the features of the image and then do the experiment of image retrieval.

在 2019-06-09 19:29:47，"Matiur Rahman Minar" <notifications@github.com> 写道：


How to extract image features using ResNet101 under tensorflow？

@flyinsky323, Could you please be more specific what you are trying to do? Anyway, this repository is just slightly modified version of this: https://github.com/DrSleep/tensorflow-deeplab-resnet, for working with python 3. You may find your answers from the original repository discussions as well.

**Comment by flyinsky323** [comment]
> > How to extract image features using ResNet101 under tensorflow？
> 
> @flyinsky323, Could you please be more specific what you are trying to do? Anyway, this repository is just slightly modified version of this: https://github.com/DrSleep/tensorflow-deeplab-resnet, for working with python 3. You may find your answers from the original repository discussions as well.

**Comment by flyinsky323** [comment]
> > How to extract image features using ResNet101 under tensorflow？
> 
> @flyinsky323, Could you please be more specific what you are trying to do? Anyway, this repository is just slightly modified version of this: https://github.com/DrSleep/tensorflow-deeplab-resnet, for working with python 3. You may find your answers from the original repository discussions as well.

I need to extract the features of the image and then do the experiment of image retrieval.

**Comment by minar09** [comment]
@flyinsky323 I see. Well, DeepLabV2 is mainly a segmentation network, however its extracting the image features with ResNet101 first. Then resize the prediction for segmentation output.
https://github.com/minar09/DeepLabV2-ResNet101-TensorFlow/blob/master/deeplab_resnet/model.py is the ResNet network here. You may use the model for your purpose (Also look at the train.py file how they process images). Although, for your convenience, I suggest you look for other ResNet only repository for image retrieval.
